export const NOTIFICATION_TYPES = Object.freeze({
  APPLICATION_SUBMITTED: "APPLICATION_SUBMITTED",
  DOCUMENT_MISSING: "DOCUMENT_MISSING",
  PAYMENT_RECEIPT_RECORDED: "PAYMENT_RECEIPT_RECORDED",
  PAYMENT_CONFIRMED: "PAYMENT_CONFIRMED",
  INQUIRY_RECEIVED: "INQUIRY_RECEIVED",
  INQUIRY_RESPONDED: "INQUIRY_RESPONDED",
  APPLICATION_ROUTED: "APPLICATION_ROUTED",
  COMMITTEE_ACTION_REQUIRED: "COMMITTEE_ACTION_REQUIRED",
  DECISION_ISSUED: "DECISION_ISSUED",
  DOCUMENT_READY: "DOCUMENT_READY",
});

export const NOTIFICATION_FILTERS = Object.freeze({
  ALL: "ALL",
  UNREAD: "UNREAD",
});

export default NOTIFICATION_TYPES;
