export const WORKFLOW_STAGES = Object.freeze({
  SUBMITTED: "SUBMITTED",
  PAYMENT: "PAYMENT",
  DOCUMENTS: "DOCUMENTS",
  PAPER_RECEIVING: "PAPER_RECEIVING",
  STUDY: "STUDY",
  INSTITUTION_VERIFICATION: "INSTITUTION_VERIFICATION",
  CREDENTIAL_INQUIRY: "CREDENTIAL_INQUIRY",
  INQUIRY_WAITING: "INQUIRY_WAITING",
  INQUIRY_FOLLOW_UP: "INQUIRY_FOLLOW_UP",
  INQUIRY_RESULT: "INQUIRY_RESULT",
  ROUTING: "ROUTING",
  SPECIALIZED_COMMITTEE: "SPECIALIZED_COMMITTEE",
  HIGHER_COMMITTEE: "HIGHER_COMMITTEE",
  DRAFT: "DRAFT",
  FINALIZATION: "FINALIZATION",
  ARCHIVE: "ARCHIVE",
  DELIVERY: "DELIVERY",
  COMPLETED: "COMPLETED",
  NON_EQUIVALENT: "NON_EQUIVALENT",
  FRAUD: "FRAUD",
});

export const COMMITTEE_TYPES = Object.freeze({
  SECONDARY: "SECONDARY",
  UNIVERSITY: "UNIVERSITY",
  SPECIALIZED: "SPECIALIZED",
  HIGHER: "HIGHER",
});

export const INQUIRY_STATES = Object.freeze({
  PREPARING: "PREPARING",
  SENT: "SENT",
  WAITING_RESPONSE: "WAITING_RESPONSE",
  FOLLOW_UP: "FOLLOW_UP",
  RESPONSE_RECEIVED: "RESPONSE_RECEIVED",
  RESULT_OK: "RESULT_OK",
  RESULT_NOT_OK: "RESULT_NOT_OK",
});

export const COMMITTEE_RESULTS = Object.freeze({
  EQUIVALENT: "EQUIVALENT",
  POSTPONED: "POSTPONED",
  NOT_EQUIVALENT: "NOT_EQUIVALENT",
  NEW_INQUIRY: "NEW_INQUIRY",
  ADDITIONAL_DOCUMENT: "ADDITIONAL_DOCUMENT",
  RETURN_TO_TECHNICAL: "RETURN_TO_TECHNICAL",
});

export const WORKFLOW_STEPS = [
  { key: WORKFLOW_STAGES.SUBMITTED, labelKey: "workflow.submitted" },
  { key: WORKFLOW_STAGES.PAYMENT, labelKey: "workflow.payment" },
  { key: WORKFLOW_STAGES.DOCUMENTS, labelKey: "workflow.documents" },
  { key: WORKFLOW_STAGES.PAPER_RECEIVING, labelKey: "workflow.paperReceiving" },
  { key: WORKFLOW_STAGES.STUDY, labelKey: "workflow.study" },
  { key: WORKFLOW_STAGES.INSTITUTION_VERIFICATION, labelKey: "workflow.institutionVerification" },
  { key: WORKFLOW_STAGES.CREDENTIAL_INQUIRY, labelKey: "workflow.credentialInquiry" },
  { key: WORKFLOW_STAGES.ROUTING, labelKey: "workflow.routing" },
  { key: WORKFLOW_STAGES.SPECIALIZED_COMMITTEE, labelKey: "workflow.specializedCommittee" },
  { key: WORKFLOW_STAGES.HIGHER_COMMITTEE, labelKey: "workflow.higherCommittee" },
  { key: WORKFLOW_STAGES.DRAFT, labelKey: "workflow.draft" },
  { key: WORKFLOW_STAGES.FINALIZATION, labelKey: "workflow.finalization" },
  { key: WORKFLOW_STAGES.DELIVERY, labelKey: "workflow.delivery" },
];
