/**
 * Canonical frontend permission vocabulary.
 * Backend authorization remains the real security boundary.
 */
export const PERMISSIONS = Object.freeze({
  AUTHENTICATED: "AUTHENTICATED",

  VIEW_ROLE_PROFILE: "VIEW_ROLE_PROFILE",
  VIEW_APPLICATIONS: "VIEW_APPLICATIONS",
  APPLICATION_CREATE: "APPLICATION_CREATE",
  APPLICATION_VIEW_OWN: "APPLICATION_VIEW_OWN",
  APPLICATION_EDIT_OWN: "APPLICATION_EDIT_OWN",
  APPLICATION_REVIEW: "APPLICATION_REVIEW",

  DOCUMENT_UPLOAD_OWN: "DOCUMENT_UPLOAD_OWN",
  RECEIVE_PAPER: "RECEIVE_PAPER",
  REVIEW_PAPER: "REVIEW_PAPER",
  ARCHIVE_DOCUMENT: "ARCHIVE_DOCUMENT",

  PAYMENT_VIEW_OWN: "PAYMENT_VIEW_OWN",
  PAYMENT_RECORD: "PAYMENT_RECORD",
  PAYMENT_CONFIRM: "PAYMENT_CONFIRM",

  UNIVERSITY_VERIFY: "UNIVERSITY_VERIFY",
  CREDENTIAL_VERIFY: "CREDENTIAL_VERIFY",
  ROUTE_APPLICATION: "ROUTE_APPLICATION",
  HOLD_APPLICATION: "HOLD_APPLICATION",

  MANAGE_INQUIRIES: "MANAGE_INQUIRIES",

  COMMITTEE_VIEW: "COMMITTEE_VIEW",
  COMMITTEE_COORDINATE: "COMMITTEE_COORDINATE",
  COMMITTEE_REVIEW: "COMMITTEE_REVIEW",
  COMMITTEE_RECORD: "COMMITTEE_RECORD",
  HIGHER_COMMITTEE_REVIEW: "HIGHER_COMMITTEE_REVIEW",

  PRINT_DRAFT: "PRINT_DRAFT",
  MANAGE_DRAFT: "MANAGE_DRAFT",
  PRINT_FINAL: "PRINT_FINAL",

  REPORTS_VIEW: "REPORTS_VIEW",
  MANAGE_USERS: "MANAGE_USERS",

  DRAFT_REVIEW_OWN: "DRAFT_REVIEW_OWN",
  APPEAL_CREATE_OWN: "APPEAL_CREATE_OWN",
  DELIVERY: "DELIVERY",
  POST_DECISION_SERVICE_VIEW: "POST_DECISION_SERVICE_VIEW",
  POST_DECISION_SERVICE_MANAGE: "POST_DECISION_SERVICE_MANAGE",
});

export const ALL_PERMISSIONS = Object.freeze(Object.values(PERMISSIONS));

export default PERMISSIONS;


