import { PERMISSIONS, ALL_PERMISSIONS } from "./permissions";

export const ROLES = Object.freeze({
  ADMIN: "ADMIN",
  MANAGER: "MANAGER",
  EQUIVALENCY: "EQUIVALENCY",
  RECEIVING: "RECEIVING",
  INQUIRY: "INQUIRY",
  ARCHIVE: "ARCHIVE",
  COMMITTEE_COORDINATOR: "COMMITTEE_COORDINATOR",
  COMMITTEE_MEMBER: "COMMITTEE_MEMBER",
  OFFICE: "OFFICE",
  PRINTING: "PRINTING",
  APPLICANT: "APPLICANT",
});

export const ROLE_LABELS = Object.freeze({
  [ROLES.ADMIN]: {
    ar: "مدير النظام",
    en: "System Administrator",
  },
  [ROLES.MANAGER]: {
    ar: "مدير دائرة المعادلة",
    en: "Equivalency Manager",
  },
  [ROLES.EQUIVALENCY]: {
    ar: "موظف المعادلات",
    en: "Equivalency Officer",
  },
  [ROLES.RECEIVING]: {
    ar: "موظف الاستقبال",
    en: "Receiving Officer",
  },
  [ROLES.INQUIRY]: {
    ar: "موظف الاستعلامات",
    en: "Inquiry Officer",
  },
  [ROLES.ARCHIVE]: {
    ar: "موظف الأرشيف",
    en: "Archive Officer",
  },
  [ROLES.COMMITTEE_COORDINATOR]: {
    ar: "منسق اللجان",
    en: "Committee Coordinator",
  },
  [ROLES.COMMITTEE_MEMBER]: {
    ar: "عضو اللجنة",
    en: "Committee Member",
  },
  [ROLES.OFFICE]: {
    ar: "موظف مكتب التعليم العالي",
    en: "Higher Education Office Officer",
  },
  [ROLES.PRINTING]: {
    ar: "موظف الطباعة",
    en: "Printing Officer",
  },
  [ROLES.APPLICANT]: {
    ar: "مقدم الطلب",
    en: "Applicant",
  },
});

const APPLICANT = [
  PERMISSIONS.AUTHENTICATED,
  PERMISSIONS.APPLICATION_CREATE,
  PERMISSIONS.APPLICATION_VIEW_OWN,
  PERMISSIONS.APPLICATION_EDIT_OWN,
  PERMISSIONS.DOCUMENT_UPLOAD_OWN,
  PERMISSIONS.PAYMENT_VIEW_OWN,
  PERMISSIONS.DRAFT_REVIEW_OWN,
  PERMISSIONS.APPEAL_CREATE_OWN,
  PERMISSIONS.POST_DECISION_SERVICE_VIEW,
  PERMISSIONS.VIEW_ROLE_PROFILE,
];

const MANAGER = [
  PERMISSIONS.AUTHENTICATED, PERMISSIONS.VIEW_ROLE_PROFILE,
  PERMISSIONS.VIEW_APPLICATIONS, PERMISSIONS.APPLICATION_REVIEW,
  PERMISSIONS.UNIVERSITY_VERIFY, PERMISSIONS.CREDENTIAL_VERIFY,
  PERMISSIONS.ROUTE_APPLICATION, PERMISSIONS.HOLD_APPLICATION,
  PERMISSIONS.COMMITTEE_VIEW, PERMISSIONS.COMMITTEE_COORDINATE,
  PERMISSIONS.HIGHER_COMMITTEE_REVIEW, PERMISSIONS.REPORTS_VIEW,
  PERMISSIONS.POST_DECISION_SERVICE_VIEW, PERMISSIONS.POST_DECISION_SERVICE_MANAGE,
];

export const ROLE_PERMISSIONS = Object.freeze({
  [ROLES.ADMIN]: ALL_PERMISSIONS,
  [ROLES.MANAGER]: MANAGER,
  [ROLES.EQUIVALENCY]: [
    PERMISSIONS.AUTHENTICATED, PERMISSIONS.VIEW_ROLE_PROFILE, PERMISSIONS.VIEW_APPLICATIONS,
    PERMISSIONS.APPLICATION_REVIEW, PERMISSIONS.UNIVERSITY_VERIFY, PERMISSIONS.CREDENTIAL_VERIFY,
    PERMISSIONS.ROUTE_APPLICATION, PERMISSIONS.HOLD_APPLICATION,
    PERMISSIONS.POST_DECISION_SERVICE_VIEW, PERMISSIONS.POST_DECISION_SERVICE_MANAGE,
  ],
  [ROLES.RECEIVING]: [PERMISSIONS.AUTHENTICATED, PERMISSIONS.VIEW_ROLE_PROFILE, PERMISSIONS.VIEW_APPLICATIONS, PERMISSIONS.RECEIVE_PAPER, PERMISSIONS.REVIEW_PAPER, PERMISSIONS.PAYMENT_RECORD, PERMISSIONS.PAYMENT_CONFIRM, PERMISSIONS.POST_DECISION_SERVICE_VIEW],
  [ROLES.INQUIRY]: [PERMISSIONS.AUTHENTICATED, PERMISSIONS.VIEW_ROLE_PROFILE, PERMISSIONS.VIEW_APPLICATIONS, PERMISSIONS.MANAGE_INQUIRIES, PERMISSIONS.POST_DECISION_SERVICE_VIEW, PERMISSIONS.POST_DECISION_SERVICE_MANAGE],
  [ROLES.ARCHIVE]: [PERMISSIONS.AUTHENTICATED, PERMISSIONS.VIEW_ROLE_PROFILE, PERMISSIONS.VIEW_APPLICATIONS, PERMISSIONS.ARCHIVE_DOCUMENT, PERMISSIONS.POST_DECISION_SERVICE_VIEW, PERMISSIONS.POST_DECISION_SERVICE_MANAGE],
  [ROLES.COMMITTEE_COORDINATOR]: [PERMISSIONS.AUTHENTICATED, PERMISSIONS.VIEW_ROLE_PROFILE, PERMISSIONS.VIEW_APPLICATIONS, PERMISSIONS.COMMITTEE_VIEW, PERMISSIONS.COMMITTEE_COORDINATE, PERMISSIONS.COMMITTEE_RECORD, PERMISSIONS.HIGHER_COMMITTEE_REVIEW, PERMISSIONS.POST_DECISION_SERVICE_VIEW],
  [ROLES.COMMITTEE_MEMBER]: [PERMISSIONS.AUTHENTICATED, PERMISSIONS.VIEW_ROLE_PROFILE, PERMISSIONS.COMMITTEE_VIEW, PERMISSIONS.COMMITTEE_REVIEW, PERMISSIONS.COMMITTEE_RECORD, PERMISSIONS.POST_DECISION_SERVICE_VIEW],
  [ROLES.OFFICE]: [PERMISSIONS.AUTHENTICATED, PERMISSIONS.VIEW_ROLE_PROFILE, PERMISSIONS.DELIVERY],
  [ROLES.PRINTING]: [PERMISSIONS.AUTHENTICATED, PERMISSIONS.VIEW_ROLE_PROFILE, PERMISSIONS.VIEW_APPLICATIONS, PERMISSIONS.PRINT_DRAFT, PERMISSIONS.MANAGE_DRAFT, PERMISSIONS.PRINT_FINAL, PERMISSIONS.ARCHIVE_DOCUMENT, PERMISSIONS.POST_DECISION_SERVICE_VIEW, PERMISSIONS.POST_DECISION_SERVICE_MANAGE],
  [ROLES.APPLICANT]: APPLICANT,
});

export const isKnownRole = (role) => Object.values(ROLES).includes(role);
export default ROLES;



